runtime: nodejs20
env: standard
handlers:
- url: /static
  static_dir: build/static
- url: /(.*\.(json|ico|jpg|jpeg|png|gif|svg|webp|txt|css|js))$
  static_files: build/\1
  upload: build/.*\.(json|ico|jpg|jpeg|png|gif|svg|webp|txt|css|js)$
- url: /api/.*
  script: auto
- url: /.*
  static_files: build/index.html
  upload: build/index.html
vpc_access_connector:
  name: projects/hku-capstone-project-458309/locations/asia-east2/connectors/hku-vpc-connector-subnet
env_variables:
  BACKEND_VM_INTERNAL_IP: "10.170.0.30"
  BACKEND_VM_PORT: "8000"
