runtime: nodejs20 # Or appropriate Node.js version
env: standard
handlers:
- url: /static
  static_dir: build/static
- url: /(.*\.(json|ico|jpg|jpeg|png|gif|svg|webp|txt|css|js))$
  static_files: build/\1
  upload: build/.*\.(json|ico|jpg|jpeg|png|gif|svg|webp|txt|css|js)$
- url: /.*
  static_files: build/index.html
  upload: build/index.html
